### ISSUE TITLE
1s samples eventually stop being collected at a 1 Hz rate

### ISSUE THREAD

**Issue by twest820** [Arpapiemonte/openoise-meter#6]
Leave a measurement running long enough (not sure of the exact onset point, but tens of minutes) and its update rate degrades. ~2 Hz, ~3 Hz, potentially not at all with the UX hanging and the start, pause, stop, and reset buttons stop responding. This is a regression in OpeNoise 3.0.3 from earlier (pre-3.0) versions. When possible, stopping and resetting the measurement doesn't clear the issue and neither does starting a new measurement. So far, swiping up to kick OpeNoise out of active app status and then restarting a measurement does seem to restore stable 1s sampling.

From observed behavior it seems plausible the app might lock up for some users and have to be force stopped, though that's not something I've observed as yet. I'll update this issue with additional observations if 3.0.3+ exhibits other behavior than what's noted above.

**Comment by Arpapiemonte** [comment]
Hi,
We have done some tests after your issue, using a Redmi Note 9 Xiami smartphone / Android 12 (april 2021).
As you can see in the attached file for three indipendent measurement sessions of more than 20 minutes, we have never encountered such a problem, the seconds are always correctly progressed.
We can imagine that the problem starts in some phones as a performance problem, connected with how many apps are open in background or with intrinsec hardware.
Could you send us:
- a measurement file with error (please use OpeNoise closing all the others apps and in plane mode, in order to have the phone in the better conditions)
- phone model and Android version

 

Thank you.
[Test.xlsx](https://github.com/Arpapiemonte/openoise-meter/files/12427077/Test.xlsx)

**Comment by twest820** [comment]
I'll turn on saving next time I'm doing a long sequence of measurements and also try some synthetic testing. Primary report's from Android 13 on an S21 but logs may end up being Android 9 on an S8 or some other version—given recent issues I'm trying to collect other phones for a broader look, means they'll likely be older ones no longer in primary use.

OpeNoise's pretty well the only app in use during measurement sessions, so all other apps are closed in at least one sense of the word. I've never seen the S21 show low resources but will check (though that does mean opening the settings app).

Also, if it's just the UX lagging in rendering then measurement files might not show a problem.

**Comment by twest820** [comment]
I've had sample rates drop to 0.25 Hz within 52 s of starting a measurement.

OpeNoise appears to use samples as its measurement clock, assuming each is at 1 Hz. So, for example, in a minute of wall clock time OpeNoise will go from indicating 1m15s of measurements to 1m30s.

Measurement files are also affected. A 1 s sample rate is claimed in wall clock time but the total measurement time is underreported and, if samples were really still at 1 Hz, there would be many more of them.

**Comment by Arpapiemonte** [comment]
We did a lot of measurements, and we never get this behaviour.
Also our set of tester (professionals in the acoustics industry) never tell us nothing like this.
The difficulty in the development of a noise meter for mobile devices is that the hardware is so different from each model. This is much more evident for android device, because of the great number of brands and models.

What we can say, is that your model has this problems. If we manage to get one, we will try, can you confirm that it's a Samsung Galaxy S21 with Android 13?

**Comment by twest820** [comment]
Both S8 and S21 are affected. It's great that the in house test devices aren't affected but, since I don't work for Arpa Piemonte, those aren't phones I've access to. The market analyses I'm aware of put Samsung as the largest phone manufacturer and, lately, the company's been saying the S series is the majority of its sales. So the use cases here appear to be about as mainline as it gets for an Android app.

I'll need to run 2.0.3 more on the S8 but, in over a year of using 2.0.3 on the S21, this issue hasn't occurred with 2.0.3. Whereas I hit the first time using 3.0.3 on the S21 and 3.0.4 on the S8. Since Android 13 only pushed a couple weeks ago that's necessarily mostly use with Android 12 on the S21. Routine OS and app updates aside, the S21's use pattern's been stable the whole time. So the only major variable looks like changing between OpeNoise 2.0 and 3.0. With 3.0's fairly short time to failure on both phones it doesn't seem a difficult repro.

Given a beta drop which writes system times rather than internal counts I could produce log files more clearly showing the problem. That won't add any new information here, though, since we already know this assumption in audio.service.ts doesn't hold:
```
 this.setIntervalCapture = setInterval(function () {
      this_copy.date_now = new Date(this_copy.date_start)
      this_copy.date_now.setSeconds(this_copy.date_start.getSeconds() + this_copy.countInterval);
      this_copy.countInterval++
      ....
    }, 1000)
```
I don't know `setInterval()` on Android but FWIW, in the other non-realtime OSes I've coded on, similar functions have had guidance in their documentation saying not to assume the timer fires at the requested rate and not to assume all timer events will be delivered. So I'm not too surprised there are problems around this though, since 1 Hz is pretty slow and OpeNoise shouldn't be doing much processing in response to the interval events, I am a bit surprised it's bogging this readily.

One option would be a beta which logs the starting and ending time of `setIntervalcapture` at millisecond resolution along with other performance telemetry. While that might not give direct insight into where the problem is it would at least narrow the set of possible failure mechanisms.

**Comment by Arpapiemonte** [comment]
In the OpeNoise 3.x test phase, we saved also the milliseconds in the data file, and no problems with any device: obviously we cannot obtain exactly 1 second, but difference are very little (some ms).
Because, if the measurement starts around the 00 sec, we can have in the log file two seconds identical (for example if the data is recorded with a difference 950 ms) or the lack of one second (if the data is recorded with a difference around 1015 ms), we finally chose to increase the seconds with an incremental fixed sec, as you saw in the code.
In any case, you can download a beta version with the miliseconds (and other beta features, you can also see -20 dB range axes), here: 
https://github.com/Arpapiemonte/openoise-meter/releases/tag/tag_1-1s-sample-c1

Make your tests and send us somethings to see your problem.
Here I attached a file where you can see for my personal phone (REALME GT MASTER - Android 13) the difference in milliseconds between one second and another (the biggest is 68 millisecs, and in general the differences are sometime positive and sometime negative, and sometime perfect).

[2023-08-30-153855.txt](https://github.com/Arpapiemonte/openoise-meter/files/12476864/2023-08-30-153855.txt)

CLARIFICATIONS:
Tester are not only Arpa Piemonte worker, but also indipendent universitary teachers and students.
Additionally, OpeNoise is installed on more then 10000 devices... nbody notified us this rate sample problem.

P.S. 
We hope we can resolve this problem, and more we hope you can help us and became an OpeNoise's developer after this issue!
You said you're familiar with 5 languages... One great thing (and very easy) is to translate in more languages OpeNoise!

**Comment by twest820** [comment]
I don't see any new diagnostic information in the 3.0.7-beta log files but here's a couple examples of declining sampling rates. If I let the traces run longer it seems likely they'd drop below 0.1 Hz.

From what I can tell, this seems linked to resetting measurements. Without resets I get steady ~1 Hz sampling for 30+ minutes. The measurement protocols we use motivate a reset every 20–45 s or so, depending on setup time for the next measurement, what exactly's getting measured, and if some other noise occurs which needs to be excluded. One possibility might be reset isn't unscheduling `setInterval()` timers from previous measurements. Another's an async state handling issue where, eventually, the timing of when reset's pressed happens to induce some sort of processing problem.
<details><summary>log 1</summary><p>
Date;Time;LAeq(t);LAeq(1s)<br>
30/08/2023;13:01:18.744;28.1;21.2<br>
30/08/2023;13:01:21.763;27.9;20.3<br>
30/08/2023;13:01:24.756;27.8;19.7<br>
30/08/2023;13:01:27.742;27.7;19.5<br>
30/08/2023;13:01:30.783;27.6;19.6<br>
30/08/2023;13:01:33.951;27.4;19.5<br>
30/08/2023;13:01:36.943;27.6;30.6<br>
30/08/2023;13:01:39.921;27.5;24.1<br>
30/08/2023;13:01:42.897;27.4;19.7<br>
30/08/2023;13:01:45.888;27.3;19.8<br>
30/08/2023;13:01:48.911;27.2;19.6<br>
30/08/2023;13:01:51.909;27.1;19.8<br>
30/08/2023;13:01:54.899;27.0;19.8<br>
30/08/2023;13:01:58.067;28.2;38.2<br>
30/08/2023;13:02:01.021;28.2;28.5<br>
30/08/2023;13:02:04.223;28.2;22.5<br>
30/08/2023;13:02:07.034;28.1;20.5<br>
30/08/2023;13:02:10.201;28.0;20.6<br>
30/08/2023;13:02:13.186;38.0;54.1<br>
30/08/2023;13:02:16.169;41.8;56.2<br>
30/08/2023;13:02:19.191;41.7;24.3<br>
30/08/2023;13:02:22.372;41.6;27.6<br>
30/08/2023;13:02:26.086;41.6;38.7<br>
30/08/2023;13:02:29.259;41.7;45.4<br>
30/08/2023;13:02:32.251;41.6;23.3<br>
30/08/2023;13:02:35.283;41.5;21.0<br>
30/08/2023;13:02:38.278;41.5;28.5<br>
30/08/2023;13:02:41.251;41.4;22.9<br>
30/08/2023;13:02:44.236;41.3;23.3<br>
30/08/2023;13:02:47.213;41.2;24.3<br>
30/08/2023;13:02:50.384;41.1;22.9<br>
30/08/2023;13:02:54.317;41.0;21.2<br>
30/08/2023;13:02:58.402;40.9;21.0<br>
30/08/2023;13:03:02.295;40.9;20.4<br>
30/08/2023;13:03:05.279;40.8;21.9<br>
30/08/2023;13:03:08.309;40.7;21.8<br>
30/08/2023;13:03:12.564;40.6;21.3<br>
30/08/2023;13:03:16.448;40.5;21.8<br>
30/08/2023;13:03:20.503;40.4;22.6<br>
30/08/2023;13:03:24.435;40.4;26.8<br>
30/08/2023;13:03:28.517;40.3;29.1<br>
30/08/2023;13:03:32.237;40.2;25.6<br>
30/08/2023;13:03:35.407;40.1;24.0<br>
30/08/2023;13:03:39.510;40.1;22.9<br>
30/08/2023;13:03:43.398;40.0;22.3<br>
30/08/2023;13:03:47.474;39.9;30.7<br>
30/08/2023;13:03:51.549;39.9;25.9<br>
30/08/2023;13:03:55.481;39.8;25.4<br>
30/08/2023;13:03:59.564;39.7;25.7<br>
30/08/2023;13:04:03.461;39.6;23.8<br>
30/08/2023;13:04:07.535;39.6;27.9<br>
30/08/2023;13:04:11.432;39.5;24.5<br>
30/08/2023;13:04:15.537;39.4;30.1<br>
30/08/2023;13:04:19.432;39.4;22.1<br>
30/08/2023;13:04:23.501;39.4;40.2<br>
30/08/2023;13:04:27.410;39.3;32.8<br>
30/08/2023;13:04:31.525;39.3;19.5<br>
30/08/2023;13:04:35.426;39.2;19.7<br>
30/08/2023;13:04:39.492;39.2;19.7<br>
30/08/2023;13:04:43.561;39.1;20.6<br>
30/08/2023;13:04:47.328;39.0;19.9<br>
30/08/2023;13:04:51.433;39.0;19.6<br>
30/08/2023;13:04:55.514;38.9;19.7<br>
30/08/2023;13:04:59.397;38.9;20.0<br>
30/08/2023;13:05:03.499;38.8;19.5<br>
30/08/2023;13:05:07.579;38.7;19.7<br>
30/08/2023;13:05:11.473;38.7;19.7<br>
30/08/2023;13:05:15.536;38.6;19.5<br>
30/08/2023;13:05:19.472;38.6;19.7<br>
30/08/2023;13:05:23.557;38.5;19.8<br>
30/08/2023;13:05:27.660;44.6;0.0<br>
30/08/2023;13:05:28.658;44.6;0.0<br>
30/08/2023;13:05:29.659;44.6;0.0<br>
30/08/2023;13:05:32.342;19.6;19.6<br>
30/08/2023;13:05:33.399;19.6;19.6<br>
30/08/2023;13:05:34.710;19.6;19.6<br>
30/08/2023;13:05:35.783;19.6;19.7<br>
30/08/2023;13:05:37.050;19.8;20.4<br>
30/08/2023;13:05:39.308;19.8;19.7<br>
30/08/2023;13:05:41.369;19.9;20.5<br>
30/08/2023;13:05:43.621;20.0;20.1<br>
30/08/2023;13:05:45.899;20.0;20.0<br>
30/08/2023;13:05:47.965;19.9;19.8<br>
30/08/2023;13:05:51.455;19.9;19.9<br>
30/08/2023;13:05:54.714;20.0;20.0<br>
30/08/2023;13:05:57.990;23.3;30.2<br>
30/08/2023;13:06:02.446;24.5;28.5<br>
30/08/2023;13:06:06.696;24.1;19.5<br>
30/08/2023;13:06:10.999;23.8;19.5<br>
30/08/2023;13:06:16.648;23.5;19.5<br>
30/08/2023;13:06:22.106;23.5;24.1<br>
30/08/2023;13:06:28.385;24.7;29.4<br>
30/08/2023;13:06:35.094;24.4;19.8<br>
30/08/2023;13:06:42.558;24.1;19.7<br>
30/08/2023;13:06:50.227;23.8;19.5<br>
30/08/2023;13:06:59.121;23.5;19.6<br>
30/08/2023;13:07:08.793;27.7;35.8<br>
</p></details> 
<details><summary>log 2</summary><p>
Date;Time;LAeq(t);LAeq(1s)<br>
30/08/2023;13:49:32.387;28.1;29.8<br>
30/08/2023;13:49:34.564;27.9;25.4<br>
30/08/2023;13:49:36.534;27.7;21.5<br>
30/08/2023;13:49:38.854;27.4;21.7<br>
30/08/2023;13:49:41.787;27.3;25.7<br>
30/08/2023;13:49:44.867;27.2;26.7<br>
30/08/2023;13:49:48.206;27.6;30.6<br>
30/08/2023;13:49:51.290;27.5;26.0<br>
30/08/2023;13:49:54.359;27.4;24.3<br>
30/08/2023;13:49:57.441;27.2;23.9<br>
30/08/2023;13:50:00.704;27.1;23.4<br>
30/08/2023;13:50:04.764;26.9;23.1<br>
30/08/2023;13:50:08.960;26.7;21.9<br>
30/08/2023;13:50:13.144;26.5;23.7<br>
30/08/2023;13:50:17.138;26.7;28.4<br>
30/08/2023;13:50:21.352;26.6;26.5<br>
30/08/2023;13:50:25.166;26.6;25.5<br>
30/08/2023;13:50:29.345;26.4;21.9<br>
30/08/2023;13:50:33.511;26.3;23.2<br>
30/08/2023;13:50:37.717;26.3;24.4<br>
30/08/2023;13:50:42.861;26.2;25.1<br>
30/08/2023;13:50:47.846;26.2;25.9<br>
30/08/2023;13:50:52.996;26.3;27.6<br>
30/08/2023;13:50:58.202;26.2;24.3<br>
30/08/2023;13:51:03.378;26.5;30.4<br>
30/08/2023;13:51:08.297;26.6;28.3<br>
30/08/2023;13:51:13.647;26.5;24.4<br>
30/08/2023;13:51:19.710;26.4;24.2<br>
30/08/2023;13:51:25.776;26.4;26.1<br>
30/08/2023;13:51:32.081;26.5;27.2<br>
30/08/2023;13:51:38.151;26.4;25.1<br>
30/08/2023;13:51:44.344;26.3;22.6<br>
30/08/2023;13:51:50.319;26.2;24.5<br>
30/08/2023;13:51:56.386;26.2;25.4<br>
30/08/2023;13:52:02.422;26.3;27.6<br>
30/08/2023;13:52:08.478;26.2;24.1<br>
30/08/2023;13:52:14.742;26.1;23.3<br>
30/08/2023;13:52:21.939;26.2;27.3<br>
30/08/2023;13:52:28.984;26.1;24.6<br>
30/08/2023;13:52:35.961;26.1;23.1<br>
30/08/2023;13:52:43.315;26.0;25.0<br>
30/08/2023;13:52:50.362;26.0;24.3<br>
30/08/2023;13:52:57.349;25.9;22.4<br>
30/08/2023;13:53:04.548;26.0;29.0<br>
30/08/2023;13:53:11.789;26.5;32.6<br>
30/08/2023;13:53:19.895;27.8;37.3<br>
30/08/2023;13:53:28.014;27.8;28.1<br>
</p></details>

**Comment by Arpapiemonte** [comment]
Hi @twest820 , finally we can understand better!
So, without reset all is fine. And this is a starting point.
The problem start when you did a long measurement and press reset every 20-45 sec.

We did a rapid test with REALME GT MASTER - Android 13, as you can see all is fine. The measurement is 3 minutes without press reset, and then every 30 seconds presents a reset for other 3 minutes.

[2023-08-31-110402.txt](https://github.com/Arpapiemonte/openoise-meter/files/12484720/2023-08-31-110402.txt)

To understand better we realized a new 3.0.8-beta version: https://github.com/Arpapiemonte/openoise-meter/releases/tag/tag_1-1s-sample-c2
In this version we add:
- a marker 'RESET' in the log file when you press the button
- the option for the data format you asked in another issue

READING THE CODE
You suppose some error unscheduling `setInterval()`, and reading your error I'm agree.
In any case the code was (file `audio.service.ts `):
```js
  reset() {
    if (this.capture) {
      clearInterval(this.setIntervalCapture)
      if (this.pause) {
        this.graficiService.inizializzaGrafici()
      }
      audioinput.stop()
      this.startCapture()
    } else {
      this.resetParameters()
      this.graficiService.inizializzaGrafici()
    }
  }
```

The `clearInterval` command has to unschedule the `setInterval` timer. May be something get wrong in your case, we have to check better.
Now the code is a little bit different, but only to add the marker RESET in the log file.
```js
 reset() {
    if (this.capture) {
      clearInterval(this.setIntervalCapture)
      if (this.pause) {
        this.graficiService.inizializzaGrafici()
      }
      audioinput.stop()
      if (this.filesystemService.saveData) {
        let data = moment().format(this.variabiliService.saveOptions.date_format) + this.variabiliService.saveOptions.field + moment().format("HH:mm:ss.SSS")
        data = data + this.variabiliService.saveOptions.field + "RESET"
        this.filesystemService.appendFile(
          this.filesystemService.nameFileWriting,
          data
        )
      }
      this.startCapture()
    } else {
      this.resetParameters()
      this.graficiService.inizializzaGrafici()
    }
  }
```

To continue to understand better the error, may you send us a log file of a measurement that starts without error (say for 3 minutes), and then with the error, (after you press RESET how many time you want, in order to generate it)?
Because in the two sample you gave us we cannot see the part in which all is file and the beginning of the error.
Thanks

**Comment by twest820** [comment]
Here you go, double reset presses courtesy of #8. Interestingly, 1 Hz sampling gets restored in the interval between presses.
<details><summary>Details</summary>
<p>
Date,Time,LAeq(t),LAeq(1s)<br>
2023-09-03,18:04:59.243,-1.7,-0.9<br>
2023-09-03,18:05:00.249,-1.7,-1.8<br>
2023-09-03,18:05:01.247,-1.7,-1.7<br>
2023-09-03,18:05:02.286,-1.7,-1.7<br>
2023-09-03,18:05:03.279,-1.7,-1.5<br>
2023-09-03,18:05:04.247,-1.7,-1.8<br>
2023-09-03,18:05:05.246,-1.7,-1.7<br>
2023-09-03,18:05:06.246,-1.7,-1.7<br>
2023-09-03,18:05:07.282,-1.7,-1.7<br>
2023-09-03,18:05:08.294,-1.7,-1.6<br>
2023-09-03,18:05:09.245,-1.7,-2.0<br>
2023-09-03,18:05:10.266,-1.7,-1.8<br>
2023-09-03,18:05:11.244,-1.7,-1.9<br>
2023-09-03,18:05:12.315,-1.7,-1.9<br>
2023-09-03,18:05:13.034,RESET<br>
2023-09-03,18:05:15.045,-1.8,0.0<br>
2023-09-03,18:05:16.045,-1.8,0.0<br>
2023-09-03,18:05:17.045,-1.8,0.0<br>
2023-09-03,18:05:17.309,RESET<br>
2023-09-03,18:05:19.365,-1.9,-1.8<br>
2023-09-03,18:05:20.325,-1.9,-1.8<br>
2023-09-03,18:05:21.386,-1.8,-1.8<br>
2023-09-03,18:05:22.325,-1.8,-1.9<br>
2023-09-03,18:05:23.314,-1.8,-1.8<br>
2023-09-03,18:05:24.372,-1.8,-1.8<br>
2023-09-03,18:05:25.316,-1.9,-1.9<br>
2023-09-03,18:05:26.317,-1.9,-1.8<br>
2023-09-03,18:05:27.340,-1.9,-1.9<br>
2023-09-03,18:05:28.315,-1.9,-2.0<br>
2023-09-03,18:05:29.317,-1.9,-2.0<br>
2023-09-03,18:05:30.315,-1.8,-1.5<br>
2023-09-03,18:05:31.315,-1.8,-1.8<br>
2023-09-03,18:05:32.361,-1.8,-1.8<br>
2023-09-03,18:05:33.313,-1.8,-1.4<br>
2023-09-03,18:05:34.394,-1.8,-1.8<br>
2023-09-03,18:05:35.328,-1.8,-1.7<br>
2023-09-03,18:05:36.314,-1.8,-0.9<br>
2023-09-03,18:05:37.366,-1.7,-1.7<br>
2023-09-03,18:05:37.991,RESET<br>
2023-09-03,18:05:39.995,-1.8,0.0<br>
2023-09-03,18:05:40.996,-1.8,0.0<br>
2023-09-03,18:05:41.713,RESET<br>
2023-09-03,18:05:43.781,-1.8,-1.7<br>
2023-09-03,18:05:44.733,-1.7,-1.5<br>
2023-09-03,18:05:45.808,-1.7,-1.8<br>
2023-09-03,18:05:46.737,-1.7,-1.8<br>
2023-09-03,18:05:47.719,-1.7,-1.6<br>
2023-09-03,18:05:48.804,-1.7,-1.7<br>
2023-09-03,18:05:49.718,-1.7,-1.7<br>
2023-09-03,18:05:50.718,-1.7,-1.8<br>
2023-09-03,18:05:51.760,-1.7,-1.7<br>
2023-09-03,18:05:52.718,-1.7,-1.7<br>
2023-09-03,18:05:53.717,-1.6,-1.0<br>
2023-09-03,18:05:54.722,-1.7,-1.8<br>
2023-09-03,18:05:55.719,-1.7,-1.7<br>
2023-09-03,18:05:56.779,-1.7,-1.8<br>
2023-09-03,18:05:57.749,-1.7,-1.7<br>
2023-09-03,18:05:58.716,-1.7,-1.7<br>
2023-09-03,18:05:59.742,-1.7,-1.8<br>
2023-09-03,18:06:00.716,-1.7,-1.7<br>
2023-09-03,18:06:01.806,-1.7,-1.7<br>
2023-09-03,18:06:02.367,RESET<br>
2023-09-03,18:06:03.929,RESET<br>
2023-09-03,18:06:06.018,-1.6,-1.5<br>
2023-09-03,18:06:06.952,-1.7,-2.0<br>
2023-09-03,18:06:08.034,-1.7,-1.7<br>
2023-09-03,18:06:08.970,-1.7,-1.5<br>
2023-09-03,18:06:09.934,-1.7,-1.6<br>
2023-09-03,18:06:11.018,-1.7,-1.7<br>
2023-09-03,18:06:11.933,-1.7,-1.5<br>
2023-09-03,18:06:12.934,-1.6,-1.5<br>
2023-09-03,18:06:13.982,-1.6,-1.7<br>
2023-09-03,18:06:14.936,-1.7,-1.9<br>
2023-09-03,18:06:16.052,-1.7,-1.8<br>
2023-09-03,18:06:16.950,-1.7,-1.9<br>
2023-09-03,18:06:17.933,-1.7,-1.7<br>
2023-09-03,18:06:19.011,-1.7,-1.7<br>
2023-09-03,18:06:19.946,-1.7,-1.4<br>
2023-09-03,18:06:21.037,-1.7,-1.4<br>
2023-09-03,18:06:21.975,-1.7,-1.7<br>
2023-09-03,18:06:22.936,-1.7,-1.9<br>
2023-09-03,18:06:23.355,RESET<br>
2023-09-03,18:06:24.900,RESET<br>
2023-09-03,18:06:26.989,-1.8,-1.9<br>
2023-09-03,18:06:27.932,-1.9,-2.0<br>
2023-09-03,18:06:29.011,-1.9,-1.9<br>
2023-09-03,18:06:29.945,-1.9,-1.8<br>
2023-09-03,18:06:30.905,-1.9,-1.9<br>
2023-09-03,18:06:32.007,-1.9,-2.1<br>
2023-09-03,18:06:32.914,-1.9,-1.9<br>
2023-09-03,18:06:34.026,-1.9,-1.9<br>
2023-09-03,18:06:34.963,-1.9,-2.0<br>
2023-09-03,18:06:35.910,-1.9,-2.0<br>
2023-09-03,18:06:37.027,-1.9,-2.0<br>
2023-09-03,18:06:37.932,-1.9,-2.1<br>
2023-09-03,18:06:38.905,-1.9,-1.9<br>
2023-09-03,18:06:39.977,-1.9,-1.9<br>
2023-09-03,18:06:40.929,-1.9,-1.9<br>
2023-09-03,18:06:42.015,-1.9,-1.9<br>
2023-09-03,18:06:42.235,RESET<br>
2023-09-03,18:06:44.239,-0.9,0.0<br>
2023-09-03,18:06:45.238,-0.9,0.0<br>
2023-09-03,18:06:45.407,RESET<br>
2023-09-03,18:06:47.516,-1.8,-1.6<br>
2023-09-03,18:06:48.452,-1.6,-1.1<br>
2023-09-03,18:06:49.543,-1.5,-1.5<br>
2023-09-03,18:06:50.474,-1.5,-1.4<br>
2023-09-03,18:06:51.412,-1.6,-1.8<br>
2023-09-03,18:06:52.537,-1.6,-1.8<br>
2023-09-03,18:06:53.443,-1.6,-1.8<br>
2023-09-03,18:06:54.412,-1.6,-1.7<br>
2023-09-03,18:06:55.499,-1.7,-1.9<br>
2023-09-03,18:06:56.433,-1.7,-1.6<br>
2023-09-03,18:06:57.412,-1.7,-1.6<br>
2023-09-03,18:06:58.461,-1.7,-1.7<br>
2023-09-03,18:06:59.412,-1.7,-1.6<br>
2023-09-03,18:07:00.514,-1.7,-1.7<br>
2023-09-03,18:07:01.447,-1.7,-1.5<br>
2023-09-03,18:07:02.411,-1.7,-1.7<br>
2023-09-03,18:07:03.482,-1.7,-1.7<br>
2023-09-03,18:07:04.055,RESET<br>
2023-09-03,18:07:06.070,-1.2,0.0<br>
2023-09-03,18:07:07.060,-1.2,0.0<br>
2023-09-03,18:07:08.059,-1.2,0.0<br>
2023-09-03,18:07:08.949,RESET<br>
2023-09-03,18:07:11.075,-1.4,-1.3<br>
2023-09-03,18:07:12.006,-1.4,-1.5<br>
2023-09-03,18:07:13.088,-1.4,-1.2<br>
2023-09-03,18:07:14.025,-1.3,-0.9<br>
2023-09-03,18:07:14.965,-1.3,-1.2<br>
2023-09-03,18:07:16.086,-1.3,-1.5<br>
2023-09-03,18:07:16.990,-1.3,-1.3<br>
2023-09-03,18:07:18.107,-1.2,-0.8<br>
2023-09-03,18:07:19.051,-1.2,-1.4<br>
2023-09-03,18:07:19.990,-1.2,-1.3<br>
2023-09-03,18:07:21.107,-1.2,-1.2<br>
2023-09-03,18:07:22.007,-1.3,-1.5<br>
2023-09-03,18:07:22.957,-1.3,-1.5<br>
2023-09-03,18:07:24.056,-1.2,-0.7<br>
2023-09-03,18:07:24.139,RESET<br>
2023-09-03,18:07:25.768,RESET<br>
2023-09-03,18:07:27.908,-1.6,-1.5<br>
2023-09-03,18:07:29.055,-1.5,-1.4<br>
2023-09-03,18:07:30.001,-1.5,-1.4<br>
2023-09-03,18:07:31.109,-1.5,-1.6<br>
2023-09-03,18:07:32.052,-1.6,-1.8<br>
2023-09-03,18:07:32.994,-1.5,-1.4<br>
2023-09-03,18:07:34.094,-1.5,-1.4<br>
2023-09-03,18:07:35.037,-1.5,-1.6<br>
2023-09-03,18:07:35.984,-1.5,-1.6<br>
2023-09-03,18:07:37.096,-1.5,-1.4<br>
2023-09-03,18:07:38.030,-1.5,-1.4<br>
2023-09-03,18:07:38.960,-1.5,-1.4<br>
2023-09-03,18:07:40.065,-1.5,-1.5<br>
2023-09-03,18:07:41.047,-1.5,-1.3<br>
2023-09-03,18:07:41.978,-1.4,-0.9<br>
2023-09-03,18:07:42.059,RESET<br>
2023-09-03,18:07:42.672,RESET<br>
2023-09-03,18:07:44.947,-0.2,-0.8<br>
2023-09-03,18:07:46.149,-0.1,0.0<br>
2023-09-03,18:07:47.157,-0.2,-0.5<br>
2023-09-03,18:07:48.354,-0.3,-0.9<br>
2023-09-03,18:07:49.355,-0.5,-1.5<br>
2023-09-03,18:07:50.376,-0.6,-1.5<br>
2023-09-03,18:07:51.578,-0.7,-1.6<br>
2023-09-03,18:07:52.581,-0.8,-1.4<br>
2023-09-03,18:07:53.767,-0.9,-1.4<br>
2023-09-03,18:07:55.738,-1.0,-1.4<br>
2023-09-03,18:07:57.857,RESET<br>
2023-09-03,18:07:59.860,-0.7,0.0<br>
2023-09-03,18:08:00.862,-0.7,0.0<br>
2023-09-03,18:08:01.509,RESET<br>
2023-09-03,18:08:04.105,-1.8,-1.7<br>
2023-09-03,18:08:05.003,-1.8,-1.7<br>
2023-09-03,18:08:06.292,-1.7,-1.6<br>
2023-09-03,18:08:07.390,-1.7,-1.5<br>
2023-09-03,18:08:08.684,-1.7,-1.6<br>
2023-09-03,18:08:10.832,-1.7,-1.7<br>
2023-09-03,18:08:13.145,-1.6,-1.5<br>
2023-09-03,18:08:15.450,-1.6,-1.6<br>
2023-09-03,18:08:17.550,-1.6,-1.6<br>
2023-09-03,18:08:21.108,-1.6,-1.7<br>
2023-09-03,18:08:24.431,-0.4,3.5<br>
2023-09-03,18:08:27.760,-0.2,0.8<br>
2023-09-03,18:08:32.285,-0.2,-0.6<br>
2023-09-03,18:08:36.615,-0.3,-1.2<br>
2023-09-03,18:08:42.217,-0.4,-0.6<br>
2023-09-03,18:08:48.008,-0.5,-1.1<br>
2023-09-03,18:08:54.641,-0.5,-0.9<br>
2023-09-03,18:09:02.281,-0.5,-0.6<br>
2023-09-03,18:09:10.128,-0.5,-0.3<br>
2023-09-03,18:09:18.949,-0.6,-1.1<br>
2023-09-03,18:09:29.006,-0.7,-1.4<br>
2023-09-03,18:09:40.102,-0.7,-0.9<br>
2023-09-03,18:09:51.999,-0.7,-1.3<br>
2023-09-03,18:10:05.332,-0.8,-1.0<br>
2023-09-03,18:10:08.325,RESET<br>
2023-09-03,18:10:24.332,2.3,0.0<br>
2023-09-03,18:10:25.332,2.3,0.0<br>
2023-09-03,18:10:26.332,2.3,0.0<br>
2023-09-03,18:10:27.333,2.3,0.0<br>
2023-09-03,18:10:28.333,2.3,0.0<br>
2023-09-03,18:10:29.333,2.3,0.0<br>
2023-09-03,18:10:30.239,RESET<br>
2023-09-03,18:10:32.838,-1.2,-0.8<br>
2023-09-03,18:10:34.248,-1.3,-1.6<br>
2023-09-03,18:10:36.761,-1.5,-1.7<br>
2023-09-03,18:10:39.038,-1.5,-1.6<br>
2023-09-03,18:10:41.537,-1.5,-1.5<br>
2023-09-03,18:10:45.111,-1.5,-1.4<br>
2023-09-03,18:10:48.714,-1.5,-1.4<br>
2023-09-03,18:10:53.654,-1.4,-1.3<br>
2023-09-03,18:10:59.609,-1.4,-1.4<br>
2023-09-03,18:11:06.691,-1.4,-1.5<br>
2023-09-03,18:11:15.068,-1.4,-1.4<br>
2023-09-03,18:11:24.523,-1.4,-1.3<br>
2023-09-03,18:11:36.251,-1.4,-1.5<br>
2023-09-03,18:11:50.640,-1.4,-1.2<br>
2023-09-03,18:11:54.015,RESET<br>
2023-09-03,18:12:12.020,-1.0,0.0<br>
2023-09-03,18:12:13.020,-1.0,0.0<br>
2023-09-03,18:12:14.019,-1.0,0.0<br>
2023-09-03,18:12:15.020,-1.0,0.0<br>
2023-09-03,18:12:16.020,-1.0,0.0<br>
2023-09-03,18:12:16.188,RESET<br>
2023-09-03,18:12:18.972,-1.2,-0.9<br>
2023-09-03,18:12:20.221,-1.2,-1.3<br>
2023-09-03,18:12:22.879,-1.3,-1.5<br>
2023-09-03,18:12:25.787,-1.3,-1.3<br>
2023-09-03,18:12:29.379,-1.3,-1.3<br>
2023-09-03,18:12:34.609,-1.3,-1.3<br>
2023-09-03,18:12:41.072,-1.3,-1.2<br>
2023-09-03,18:12:48.708,-0.9,0.2<br>
2023-09-03,18:12:58.885,-0.9,-0.9<br>
2023-09-03,18:13:11.430,-0.9,-1.0<br>
2023-09-03,18:13:28.003,-1.0,-1.2<br>
</p>
</details>

**Comment by Arpapiemonte** [comment]
Ok, thanks for the file.
It's very strange, we cannot reproduce this error in any device (as you can see in the log file we shared).
So we no need double reset, nor we see the error in the second samples.
To help to understand, we released a new beta version  [OpeNoise 3.0.11-beta](https://github.com/Arpapiemonte/openoise-meter/releases/tag/tag_1-1s-samples-c4): 
You will find a debug option in the setting page.
If you check it, you'll found in the log file this parameters:
- time with ms
- seconds count from the beginning
- number of fft for second
- number of total fft
- linear value of the noise

This is an example:
<details>
  <summary>Log</summary>
Date|Time|LAeq(t)|LAeq(1s)|Marker|Time (ms)|Count (s)|N_FFT_s|N_FFT_TOT|LAeq(s)_linear
2023-09-07|15:40:00|37,1|38,2||15:39:01.842|2|6|12|39526
2023-09-07|15:40:01|35,7|25,6||15:39:02.842|3|5|17|1817
2023-09-07|15:40:02|34,5|26,3||15:39:03.842|4|6|23|2554
2023-09-07|15:40:03|33,8|25,8||15:39:04.843|5|5|28|1920
2023-09-07|15:40:04|37,8|44,2||15:39:05.843|6|5|33|131336
2023-09-07|15:40:05|39,8|44,6||15:39:06.856|7|6|39|173285
2023-09-07|15:40:06|40,5|43,8||15:39:07.844|8|5|44|118935
2023-09-07|15:40:07|40,8|42,6||15:39:08.843|9|5|49|91814
2023-09-07|15:40:08|40,4|36,4||15:39:09.843|10|6|55|26241
2023-09-07|15:40:09|40,2|35,7||15:39:10.843|11|5|60|18403
2023-09-07|15:39:11|||RESET|15:39:11.751|11|5|65|1400
2023-09-07|15:39:12|35,0|36,4||15:39:13.773|2|6|11|26228
2023-09-07|15:39:13|34,1|30,6||15:39:14.773|3|5|16|5753
2023-09-07|15:39:14|34,3|34,7||15:39:15.778|4|6|22|17784
2023-09-07|15:39:15|33,6|27,3||15:39:16.773|5|5|27|2655
2023-09-07|15:39:16|33,2|30,0||15:39:17.773|6|5|32|4978
2023-09-07|15:39:17|32,6|26,7||15:39:18.774|7|6|38|2831
2023-09-07|15:39:18|32,1|19,2||15:39:19.774|8|5|43|412
2023-09-07|15:39:19|31,5|18,0||15:39:20.793|9|6|49|376
2023-09-07|15:39:20|31,1|15,7||15:39:21.773|10|5|54|187
2023-09-07|15:39:21|30,8|16,1||15:39:22.773|11|5|59|205
2023-09-07|15:39:23|||RESET|15:39:23.589|11|5|64|194
2023-09-07|15:39:24|25,5|14,1||15:39:25.604|2|6|11|154
2023-09-07|15:39:25|24,1|15,8||15:39:26.604|3|5|16|191
2023-09-07|15:39:26|23,1|18,6||15:39:27.611|4|6|22|438
2023-09-07|15:39:27|22,5|17,9||15:39:28.606|5|5|27|311
2023-09-07|15:39:28|28,4|35,4||15:39:29.605|6|5|32|17142
2023-09-07|15:39:29|27,9|24,5||15:39:30.616|7|6|38|1698
2023-09-07|15:39:30|27,9|27,5||15:39:31.605|8|5|43|2815
2023-09-07|15:39:31|27,6|24,7||15:39:32.613|9|6|49|1787
2023-09-07|15:39:32|27,7|28,5||15:39:33.604|10|5|54|3565
2023-09-07|15:39:33|27,5|25,0||15:39:34.605|11|5|59|1568
2023-09-07|15:39:35|||RESET|15:39:35.277|11|4|63|1042
2023-09-07|15:39:36|36,2|37,8||15:39:37.295|2|6|11|36212
2023-09-07|15:39:37|35,7|34,5||15:39:38.294|3|5|16|14101
2023-09-07|15:39:38|37,6|40,4||15:39:39.315|4|6|22|65670
2023-09-07|15:39:39|37,2|34,9||15:39:40.293|5|5|27|15326
2023-09-07|15:39:40|37,0|35,8||15:39:41.293|6|5|32|18815
2023-09-07|15:39:41|37,4|39,3||15:39:42.311|7|6|38|50778
2023-09-07|15:39:42|37,1|33,5||15:39:43.294|8|5|43|11165
2023-09-07|15:39:43|36,7|24,8||15:39:44.294|9|5|48|1498
2023-09-07|15:39:44|36,2|21,7||15:39:45.295|10|6|54|894
2023-09-07|15:39:45|35,8|18,4||15:39:46.293|11|5|59|348
2023-09-07|15:39:46|||RESET|15:39:46.896|11|3|62|177
2023-09-07|15:39:47|35,1|37,9||15:39:48.917|2|6|12|37249
2023-09-07|15:39:48|35,6|36,6||15:39:49.917|3|5|17|22715
2023-09-07|15:39:49|37,0|39,4||15:39:50.917|4|6|23|52829
2023-09-07|15:39:50|36,4|32,2||15:39:51.918|5|5|28|8266
2023-09-07|15:39:51|35,7|20,6||15:39:52.918|6|5|33|571
2023-09-07|15:39:52|35,4|33,3||15:39:53.928|7|6|39|12865
2023-09-07|15:39:53|34,9|17,1||15:39:54.918|8|5|44|257
2023-09-07|15:39:54|34,4|13,0||15:39:55.949|9|6|50|120
2023-09-07|15:39:55|33,9|16,2||15:39:56.917|10|5|55|208
2023-09-07|15:39:56|33,6|19,5||15:39:57.918|11|5|60|444
2023-09-07|15:39:57|||PAUSE|15:39:58.936|12|4|64|378
2023-09-07|15:39:58|||PAUSE|15:39:59.918|13|4|64|378
2023-09-07|15:40:59|||PAUSE|15:40:00.918|14|4|64|378
2023-09-07|15:41:00|||PAUSE|15:40:01.917|15|4|64|378
2023-09-07|15:41:01|||PAUSE|15:40:02.918|16|4|64|378
2023-09-07|15:41:02|||PAUSE|15:40:03.924|17|4|64|378
2023-09-07|15:41:03|||PAUSE|15:40:04.917|18|4|64|378
2023-09-07|15:41:04|||PAUSE|15:40:05.917|19|4|64|378
2023-09-07|15:41:05|||PAUSE|15:40:06.918|20|4|64|378
2023-09-07|15:41:06|||PAUSE|15:40:07.917|21|4|64|378
2023-09-07|15:41:07|||PAUSE|15:40:08.918|22|4|64|378
2023-09-07|15:41:08|||PAUSE|15:40:09.919|23|4|64|378
2023-09-07|15:41:09|||PAUSE|15:40:10.919|24|4|64|378
2023-09-07|15:41:10|||PAUSE|15:40:11.917|25|4|64|378
2023-09-07|15:41:11|||PAUSE|15:40:12.917|26|4|64|378
2023-09-07|15:41:12|||PAUSE|15:40:13.918|27|4|64|378
2023-09-07|15:41:13|||PAUSE|15:40:14.917|28|4|64|378
2023-09-07|15:41:14|||PAUSE|15:40:15.919|29|4|64|378
2023-09-07|15:41:15|||PAUSE|15:40:16.917|30|4|64|378
2023-09-07|15:41:16|33,6|33,4||15:40:17.918|31|5|65|10877
2023-09-07|15:41:17|35,1|41,9||15:40:18.918|32|5|70|78038
2023-09-07|15:41:18|35,7|39,8||15:40:19.935|33|6|76|57850
2023-09-07|15:41:19|35,6|34,1||15:40:20.918|34|5|81|12973
2023-09-07|15:41:20|35,4|12,7||15:40:21.917|35|5|86|93
2023-09-07|15:41:21|35,1|11,5||15:40:22.919|36|6|92|85
2023-09-07|15:41:22|34,9|28,1||15:40:23.919|37|5|97|3205
2023-09-07|15:41:23|34,8|31,9||15:40:24.937|38|6|103|9353
2023-09-07|15:41:24|34,6|25,5||15:40:25.918|39|5|108|1795
2023-09-07|15:41:25|34,4|9,5||15:40:26.917|40|5|113|44
2023-09-07|15:41:26|34,2|15,4||15:40:27.920|41|6|119|208
2023-09-07|15:41:27|34,1|32,9||15:40:28.919|42|5|124|9813
2023-09-07|15:41:28|34,0|31,4||15:40:29.926|43|6|130|8316
2023-09-07|15:41:29|33,9|21,8||15:40:30.917|44|5|135|748
</details> 

Here the file:
[2023-09-07-153901.txt](https://github.com/Arpapiemonte/openoise-meter/files/12549923/2023-09-07-153901.txt)

With this release, we made a great change in the `addEventListeners` command of the `audioinput` plugin.
We realized that the `addEventListeners` command was recall every time one push Reset or Play Button!
It's a really mistery that only in your device this recalling gives problems, while in all the other models everything seems ok.
In the code (file `audio.service.ts`), from this:
```js
  // Listen to audioinput events
    window.addEventListener("audioinput", this.onAudio, false);
    //  Listen to audioinputerror events
    var onAudioInputError = function (error) {
      alert("onAudioInputError event recieved: " + JSON.stringify(error));
    };
    window.addEventListener("audioinputerror", onAudioInputError, false);
```

To this:
```js
    if (this.setEventAddListeners == false) {
      console.log("setEventAddListeners", this.setEventAddListeners)
      this.setEventAddListeners = true
      // Listen to audioinput events
      window.addEventListener("audioinput", this.onAudio, false);
      //  Listen to audioinputerror events
      var onAudioInputError = function (error) {
        alert("onAudioInputError event recieved: " + JSON.stringify(error));
      };
      window.addEventListener("audioinputerror", onAudioInputError, false);
    }
```
In this way, the app call the  `addEventListeners` command only one time.
Please, tell us if this change resolves the problem.
If not, send us a new log with the error like the last you send us, but with the new parameters.

**Comment by twest820** [comment]
Apologies for the slow response (it's been a busy couple of weeks). I've found opportunities to run several long tests, though, and the `setEventAddListeners` fix not to repeatedly hook events appears plausibly a fix for this issue as written. #8 persists, however, and the elapsed measurement time jumps by one minute whenever the system time increments by a minute (_e.g_. a wall clock tick from 15:50 to 15:51 which occurs 15.5 seconds after the most recent press of reset results in the elapsed time showing as ...00:13, 00:14, 00:15, 01:16, 01:17, 01:18... instead of ...00:13, 00:14, 00:15, 00:16, 00:17, 00:18...).

**Comment by Arpapiemonte** [comment]
Hi,
we are happy to have resolved for first point.
For the second one, we can't understand, this seems a new problem.
In your old issue #8 you said that you had to press 2 times the reset button to refresh the LAeq(1s) display (and log file), otherwise you find zero in the level: this problem was fixed?
Then the new problem "time jumps": occurs only in the display or in the log file?
Can you send us a file (with debug parameter) that reproduce the error?
Thanks

**Comment by twest820** [comment]
#8 is not fixed and thus remains active. Since elapsed time is not recorded in the log file time jumps cannot (currently) occur there.

**Comment by Arpapiemonte** [comment]
Hi,
we have released a new version [v.3.1.0](https://github.com/Arpapiemonte/openoise-meter/releases/tag/tag_1-1s-samples-c5), with:
- Added Marker functionality
- Improved save options
- Minibug fixed
- Improvement performace

Here we have also fixed this new 'elapsed time error'.
Note that we have removed the debug option in log file.

Please tell us if this version fix this issue and the #8

**Comment by twest820** [comment]
Hi, 3.1.0-beta fixes the time jump (at least over the first couple minutes of a measurement) but not #8.

**Comment by Arpapiemonte** [comment]
Ok,
thanks for all, we can finally close this 1s sample issue
